#!/usr/bin/env ruby

require 'exchange_rates_nbp'

require 'optparse'
require 'colorize'

options = {}

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: exchange_rates_nbp [options]'

  opts.on('--currency-code=CURRENCY_CODE',
          'Currency code for query') do |currency_code|
    options[:currency_code] = currency_code
  end

  opts.on('--date=DATE', 'Date for query') do |date|
    options[:date] = Date.parse(date)
  end

  opts.on('--latest', 'Print latest exchange rate') do
    options[:date] = Date.today
  end

  opts.on('-v', '--verbose', 'Show verbose info') do
    options[:verbose] = true
  end
end

parser.parse!

if options[:currency_code].nil? || options[:date].nil?
  puts '`currency_code` and `date` params are required'.red
  puts parser.help
else
  info = ExchangeRatesNBP.exchange_rate_info(options[:date],
                                             options[:currency_code])

  if options[:verbose]
    puts "Publish date: #{info[:publish_date]}"
    puts "Conversion factor: #{info[:conversion_factor]}"
    puts "Exchange rate: #{info[:exchange_rate]}"
  else
    puts info[:exchange_rate]
  end
end
